#!/bin/sh

cd ~/pr/thoughts-of-x

tmux new-session -d -s art 

tmux send-keys -t art 'jekyll serve' ENTER


tmux split-window -v

tmux send-keys -t art 'cd ~/pr/art' ENTER

tmux send-keys -t art 'tsc --watch' ENTER

tmux split-window -v


tmux send-keys -t art 'vim 00' ENTER

tmux a
