#!/bin/sh

cd ~/pr/category-theory-illustrated

tmux new-session -d -s cate

tmux send-keys -t cate 'vim .' ENTER
tmux split-window -h
tmux send-keys -cate blog 'bundle exec jekyll serve' ENTER
tmux a
